### ISSUE TITLE
Save button in AddNewExpense doesn't become to enable

### ISSUE THREAD

**Issue by runceel** [Microsoft/AppConsult-WinAppsModernizationWorkshop#25] opened 2019-04-26 07:47 UTC
After end of Exercise 3, Save button can't click just after filled all form items.

### Repro step:
- Input Type, Description, Amount, Location, City, and select date on CalendarView.

![image](https://user-images.githubusercontent.com/79868/56791580-5b46af00-6842-11e9-84cc-3d21e14203bf.png)

If setting focus any textbox control, then the Save button become to enable.

![image](https://user-images.githubusercontent.com/79868/56791722-bf697300-6842-11e9-9489-ef0f0994030e.png)

**Comment by qmatteoq** [comment] 2019-04-26 14:36
Thanks Kazuki. It seems that the problem is that the XAML Islands control doesn't trigger the focus changed event. With the starting WPF DatePicker control, when you press TAB and you move from the City field to the Date one the "CanExecute" in the ViewModel is revaluated. But it doesn't happen when you move from the City field ot the UWP Calendar control.
I'll investigate if there's an easy way to fix this. Feel free to take a look as well if you bandwidth!

**Comment by runceel** [comment] 2019-05-02 20:57
I think that the workaround of this issue is add UpdateSourceTrigger argument with PropertyChanged value to Binding of all TextBox controls in AddNewExpense.xaml.

How do you think about this workaround?

**Comment by qmatteoq** [comment] 2019-05-02 23:47
Fixed in b7a7721

**Closed by qmatteoq** 2019-05-02 23:47 UTC
Labels: bug
